DiamondLightSource/cs-web-lib

src/types/dtypes.ts
Fixing the issue where strings that are derived from char array are not displayed correctly on Egde and Chrome browsers (see GitHub Issue 3).
=> Fixing string display for browser compatibility

src/types/index.ts, src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx
The background colour of the embedded displays was hardcoded in the library class. It would be useful to be able to configure the colour from the application using the 'backgroundColor' property. This change to the library allows this.
=> Adding the ability to set the background colour of embedded displays

src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx
I have found a better and more flexible way of specifying the background colour of the Embedded displays. Previously I was relying on a property being set when creating the EmbeddedDisplay object, but actually I realised that it can be pulled straight from the OPI file. 
This has many advantages and in particular when loading dynamic pages (i.e. having different tabs load different OPIs). It removed the need for further complication in the application and relies purely on the parsing of the OPI file which is easily configurable.
=> Background color parsing

src/ui/widgets/DynamicPage/dynamicPage.tsx
If you load a display from an action button using the 'OPEN_PAGE' action, then the page gets loaded as a dynamicPage which subsequently creates an EmbeddedDisplay. By default this dynamicPage will have a cross in the corner which will close the current EmbeddedDisplay. 
In some cases I do not think this is the required behaviour, i.e. I would expect to open a view and that would be what is displayed on that page. Then if I select another button it would load a different page. I don't think there should be the option to close it as it is a little confusing.
I have added the ability to configure whether this close button is available on a dynamicPage. I have left the default behaviour to be that it is shown (so as to not change the behaviour in other instances). However adding the …
=> Configure whether a cross to close a display should be shown

src/ui/widgets/Label/label.tsx
An issue was reported where line breaks in char arrays were not being displayed. I realised that this was because the 'white-spaces' property of the css was incorrectly being set internally which is not actually necessary to perform word-wrapping and was causing the line breaks to be ignored. Removing this property and relying on the underlying css configuration fixes this issue,
=> Show line breaks

src/ui/widgets/Display/display.tsx, src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx
Fixing a scaling issue so that it only scales the opi display when the opi is larger than the screen resolution. If this is not the case then it can scale the OPI height to larger than has already been allocated leading to the bottom being chopped off. This should fix the issue described here: https://github.com/dls-controls/machine-status/issues/2
=> Fixing an OPI scaling issue 

src/connection/sim.test.ts, src/connection/sim.ts, src/ui/widgets/Image/image.test.tsx, src/ui/widgets/Image/image.tsx
This provides a solution to an issue documented in the machine-status repo (https://github.com/dls-controls/machine-status/issues/20) whereby images sourced from a server are not updated after the initial render.
See comments on the this ticket for further details.
=> Adding the simulated flipflop PV and reloading image.

package-lock.json, package.json, src/connection/coniql.test.ts, src/connection/coniql.ts
This fixes the issue described in https://github.com/dls-controls/cs-web-lib/issues/11. 
Two issues have been addressed: trying to subscribe before the websocket client is connected and the unsubscribe not fully removing the subscription from the websocket (see [comment](https://github.com/dls-controls/cs-web-lib/issues/11#issuecomment-1161558094) in issue for more details).
=> Fix duplicate graphql subscriptions

src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx
This was a bug that was missed in the PR https://github.com/dls-controls/cs-web-lib/pull/3. The embedded display height was being cropped to the screen resolution height in some cases, which is not desired behaviour. The display should only be cropped if it is larger than the screen height. I have added this check in this fix.
=> Fix a bug when scaling display causing cutoff

src/ui/widgets/Webcam/webcam.module.css, src/ui/widgets/Webcam/webcam.test.tsx, src/ui/widgets/Webcam/webcam.tsx, src/ui/widgets/index.ts
A webcam widget that displays MJPEG streams (or other compatible formats) in a HTML image. The widget expands to fill the entire window and maintains aspect ratio when window is resized in any direction. If a connection cannot be made, the alt text displays an error message informing the viewer of this.
=> Webcam widget

package-lock.json, package.json, src/types/axes.test.ts, src/types/axes.ts, src/types/props.ts, src/types/traces.test.ts, src/types/traces.ts, src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx, src/ui/widgets/EmbeddedDisplay/opiParser.test.ts, src/ui/widgets/EmbeddedDisplay/opiParser.ts, src/ui/widgets/EmbeddedDisplay/parser.ts, src/ui/widgets/XYPlot/xyPlot.tsx, src/ui/widgets/XYPlot/xyPlotOptions.test.ts, src/ui/widgets/XYPlot/xyPlotOptions.ts, src/ui/widgets/index.ts, src/ui/widgets/propTypes.ts, src/ui/widgets/utils.ts
I created an XYPlot widget based on the `dawn.xygraph` and `xygraph` widgets that uses plotly.js/react-plotly.js as the plotting library. It is able to mimic most of the existing functionality provided by CSStudio with plotly.js settings, and uses the same default values for properties. It does not currently have the ability to concatenate new data onto already plotted data. 
Some other things to note:
- The names in the .opi file for trace/axis properties are difficult to parse, so I would very much appreciate any feedback on better ways to implement the parsing! 
- Currently cs-web-lib does not correctly resolve nested macro names for PVs, as mentioned in the [Not yet implemented section in the cs-web-proto wiki](https://github.com/dls-controls/cs-web-proto/wiki/Macros). As xygraph …
=> Add plot widget

package-lock.json, package.json
This addresses the dependency issues mentioned in #18:
- Peer dependency on React 17.0.2 and above has been changed to 17.0.0 upwards. 
- Packages missing from the distribution (bufferutil and utf-8-validate) are now included
=> Fix Issue #18 dependency warnings on install

src/connection/coniql.test.ts, src/connection/coniql.ts
Fix errors thrown by the client when disconnected from the Conqil websocket. The console was full of unnecessary errors which could be logged as warnings. 
There was also a case where it tried to unsubscribe from a PV that it was not subscribed to and hence tried to remove a PV from a list that did not contain it throwing an error. 
With a page that has many PVs that are disconnected this becomes a lots of logged errors.
Refer to issue #17.
=> Fix errors thrown when disconnected

src/ui/widgets/Label/label.tsx
A previous fix was attempted in #9 by removing the CSS 'white-space' property. This was not the correct solution. The documentation suggests that the correct setting for this property is 'break-space' (see https://developer.mozilla.org/en-US/docs/Web/CSS/white-space for a definition).
=> Configure CSS to honour line breaks

package-lock.json, package.json, src/ui/widgets/XYPlot/plotly.d.ts, src/ui/widgets/XYPlot/xyPlot.tsx
This fixes an issue that was observed in applications using cs-web-lib (e.g. machine-status) and caused by the large size of react-plotly.js. The library and Plot component are so large that the size of cs-web-lib also increases. This results in operations like `npm run lint` and `npm run build` failing in applications that import cs-web-lib due to running out of memory. Increasing the available memory using `NODE_OPTIONS=--max-old-space-size=XXXX` works, but doesn't address the core issue.
I have implemented a fix for this that is referenced in [this issue](https://github.com/plotly/react-plotly.js/issues/135#issuecomment-501398125). It involves swapping the plotly.js library that react-plotly.js uses for a stripped down version plotly.js-basic-dist which only contains scatter, pie and …
=> Force react-plotly.js to use plotly.js-basic-dist

src/ui/widgets/Webcam/webcam.module.css, src/ui/widgets/Webcam/webcam.test.tsx, src/ui/widgets/Webcam/webcam.tsx
The previous implementation of the webcam widget only allowed for a single one to be displayed per page - this was due to auto-sizing of the widget being based on the window size and each webcam widget having the same id. I have updated this now so that the scaling of webcams depends on the size of parent element, and each accepts a name/id to differentiate them. The tests have also been updated for the addition of an id/name.
The webcam sizing isn't ideal as if you attempt to make the page smaller than the original webcam size l it does not shrink, but instead starts to crop the edges. I haven't figured out the exact CSS needed to achieve this.
=> Update webcam to display multiple on page

src/ui/widgets/Webcam/webcam.tsx
While implementing webcam SDMs in machine-status I noticed that despite setting `object-fit: contain` in webcam.module.css, the `img` element of the Webcam widget frequently overflows the boundaries of its parent container. This often means that the Webcam is not fully displayed on the screen. I traced the source of this to the `div` element that makes up the first layer of the Webcam widget. Because this did not have height or width specified it was expanding past the height and width of the parent element, and therefore making the `img` element overflow too. Adding in height and width ensures that the webcam widget now fills the available space but does not overflow past it, while still maintaining the aspect ratio.
=> Ensure webcam widget size doesn't overflow container

src/types/index.ts, src/ui/components/index.ts
These two components are needed by the performancePage in cs-web-proto but they are not exported by cs-web-lib so it cannot access them. This PR simply exports these components so that applications can use them from the library.
=> Export components needed in cs-web-proto

src/index.ts, src/misc/index.ts, src/types/index.ts, src/ui/components/index.ts
After removing the footer and header components from cs-web-lib (see #32), we need to add them into the cs-web-proto application. These require further exports of functions from cs-web-lib.
=> Export functions required for cs-web-proto header and footer

src/ui/widgets/Display/display.tsx, src/ui/widgets/DynamicPage/dynamicPage.tsx, src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx, src/ui/widgets/utils.ts
The autoscaling to fit the window size does get a little complicated as there multiple use cases of this. The problem relates to what you define as the scale origin. This differs for different configurations. This PR fixes/maintains behaviour for the following cases:
- machine-status displays - these displays are central in the window and so their scaling origin is "center top". This will be the default for embedded displays unless specified.
- webcam displays - the original scaling issue referenced in #28 would be fixed with this re-work, but note it was already fixed in the machine-status app by changing the positions to be absolute instead of a percentage of the window.
- dynamicPage - layouts in cs-web-proto use dynamic pages to load in an OPI. These need to have a scaling origin of …
=> Fix autoZoomToFit scaling for all observed use-cases

src/ui/widgets/index.ts
The TabContainer widget was not exported from the library and is required by cs-web-proto. I've also been through and checked that all other widgets have been exported.
=> Export TabContainer widget for use

package-lock.json, package.json, src/connection/coniql.ts
The websocket protocol library `subscription-transport-ws` has been deprecated and so users should move to the `graphql-ws` library (ref: https://www.npmjs.com/package/subscriptions-transport-ws). In this PR I have:
- changed the websocket client to use the new `graphql-ws` library to create the client,
- used the compatible `GraphQLWsLink`,
- removed a lot of the logic that we put in to handle re-connections to Coniql that are no longer needed with the new client,
- updated dependencies as required.
I have tested this against the `machine-status` application as well as a performance page updating 200 PVs at 10 Hz. I have tested different scenarios such as refreshing the browser page and disconnecting + reconnecting Coniql while the page is open. In these cases I did not see a memory leak …
=> Update to use the new `graphql-ws` websocket library

src/ui/widgets/ByteMonitor/byteMonitor.test.tsx, src/ui/widgets/ByteMonitor/byteMonitor.tsx
Updated the widget so that the sizing of LEDs now more accurately replicates CSStudio sizing. I have also improved the 3D effect appearance and updated tests.
This is their appearance now in cs-web-lib
versus how the same widgets look in CSStudio
=> Update bytemonitor widget

src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx
Changed the overflow behaviour for EmbeddedDisplay to "auto". This means that scrollbars appear when necessary, but do not appear when there is no overflow. 
This was after reported issues in Google Chrome of seeing double scrollbars even when application was in full-screen mode. Firefox hides scrollbars when not needed, so there is no difference in behaviour for this browser.
=> Change EmbeddedDisplay overflow mode to "auto"

package-lock.json, package.json, src/ui/widgets/EmbeddedDisplay/opiParser.ts, src/ui/widgets/Line/__snapshots__/line.test.tsx.snap, src/ui/widgets/Line/line.test.tsx, src/ui/widgets/Line/line.tsx
Fixed the functionality of the line widget so the behaviour more closely matches that of CSS/Phoebus
- Line is an svg `polyline` with multiple points of x,y coordinates joined by lines
- Arrowheads can be added to either or both ends of the line
- Tests updated, along with snapshot
=> Fix Line widget Issue #47

src/ui/widgets/EmbeddedDisplay/opiParser.ts
This change allows us to read files from URLs over HTTP by not calling the `normalisePath` function (which adds the directory root to the start of the path).
=> Allow files from URLs starting "http" to be fetched and parsed

src/ui/widgets/EmbeddedDisplay/bobParser.test.ts, src/ui/widgets/EmbeddedDisplay/bobParser.ts, src/ui/widgets/EmbeddedDisplay/opiParser.test.ts, src/ui/widgets/EmbeddedDisplay/parser.ts, src/ui/widgets/Readback/readback.tsx
This PR addresses 2 points:
1. By default Phoebus sets the precision to `-1` (to signal `from PV`) and show units to `true`. In this case Phoebus will not write these properties to the BOB file and they will not exist. If these properties are missing then Phoebus assumes the above. These properties are only written to the the BOB file when the precision is set to something other than `-1` or show units is `false`. The lib parser needs updating to reflect the case when these properties are missing so that the behaviour resembles that of Phoebus. In addition the `format` enumerations in Phoebus are different so these need to be parsed separately.
2. Elements in an array (from a waveform PV) do not respect the precision rules. Logic has been added to format array elements to the specified …
=> Improve BOB parsing and precision handling

src/ui/widgets/EmbeddedDisplay/bobParser.test.ts, src/ui/widgets/EmbeddedDisplay/parser.ts
Text was not getting wrapped in label widgets parsed from a BOB file. This is because by default Phoebus assumes that the `wrap_words` property is `true` and in this case does not include it in the widget definition in the BOB file. I.e. it only explicitly includes the property if it is `false`.
CS-Studio always provides this property (whether it is true or false). If it is missing from a CSS widget, then CSS defaults it to false, however I believe the strategy going forward is to prioritise Phoebus behaviour (which would be to set it true).
Also updated tests to make sure this is parsed correctly.
Before:
After:
=> Handle BOB file default word-wrap property

src/ui/hooks/useMacros.ts, src/ui/widgets/Arc/arc.tsx, src/ui/widgets/Ellipse/ellipse.tsx, src/ui/widgets/EmbeddedDisplay/bobParser.ts, src/ui/widgets/EmbeddedDisplay/opiParser.ts, src/ui/widgets/Image/image.tsx, src/ui/widgets/Label/label.tsx, src/ui/widgets/Line/line.tsx, src/ui/widgets/Polygon/polygon.tsx, src/ui/widgets/Shape/shape.tsx
Phoebus now longer has a `pv_name` field on Graphics widgets Arc, Ellipse, Image, Label, Polyline, Polygon and Rectangle. This has been replaced by a `macros` field, which can be used to specify `pv_name` or other fields (if needed for rules such as changing background colour). I've added the macros field into these widgets, and also ensured these macros get parsed with the others.
I tested this with some widgets that looked like this:
```
<widget type="rectangle" version="2.0.0">
<name>EDM Rectangle</name>
<macros>
<pv_name>PV NAME HERE</pv_name>
</macros>
<width>50</width>
<height>50</height>
<line_width>0</line_width>
<line_color>
<color name="Black" red="0" green="0" blue="0">
</color>
</line_color>
<background_color>
<color red="0" green="224" blue="0">
</color>
</background_color> …
```
=> Add graphics widget macros

README.md, package-lock.json, package.json, src/connection/coniql.ts
Repository was automatically transferred from `dls-controls/cs-web-lib` using https://gitlab.diamond.ac.uk/github/github-scripts
=> Replaced dls-controls with DiamondLightSource

rollup.config.js
For rollout versions > 8.3.3, the `declarationDir` property in tsconfig.json is ignored as mentioned here https://github.com/rollup/plugins/issues/1230. With the recent vite changes a new version of rollout 8.5.0 was pulled into the project.
This changes the location of where in the `dist` directory files are located, and so I have updated the input path corresponding to this new location. The package still works without this change when imported in another project, but will fail when running `tsc` and shows an error in vscode:
```
src/index.tsx:7:10 - error TS2305: Module '"@diamondlightsource/cs-web-lib"' has no exported member 'FileProvider'.
7 import { FileProvider, OutlineProvider } from "@diamondlightsource/cs-web-lib";
```
=> Change rollup input path

package.json, src/misc/profilerCallback.ts, src/redux/store.ts, tsconfig.json
After migrating to use vite the other day, I noticed a few issues when utilising cs-web-lib in machine-status:
- Previously added `"type": "module"` into package.json. This has now been removed because it isn't needed and causes an error when running tests in machine-status:
```
ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/node_modules/@diamondlightsource/cs-web-lib/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```
-  Vite exposes environment variables on `import.meta.env` instead of `process.env` so I had previously changed this over, but in order to maintain compatibility and allow client applications still using cra …
=> Fix vite issues

src/ui/widgets/EmbeddedDisplay/useOpiFile.ts
After updating the machine-status client to use `vite` and `vitest` I noticed that I was getting some warnings when running the tests:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
at EmbeddedDisplay (/home/user/cs-web/machine-status/node_modules/@diamondlightsource/cs-web-lib/dist/cjs/index.js:54548:42)
at LoadEmbeddedDirect (/home/user/cs-web/machine-status/src/app.tsx:39:29)
at RedirectAfterTimeout (/home/user/cs-web/machine-status/src/app.tsx:618:1)
at LoadRedirectView
at Route (/home/user/cs-web/machine-status/node_modules/react-router/cjs/react-router.js:664:29)
at Switch …
```
=> Fix state update on an unmounted component

src/ui/widgets/EmbeddedDisplay/bobParser.ts, src/ui/widgets/Image/image.tsx, src/ui/widgets/Symbol/__snapshots__/symbol.test.tsx.snap, src/ui/widgets/Symbol/symbol.module.css, src/ui/widgets/Symbol/symbol.test.tsx, src/ui/widgets/Symbol/symbol.tsx
Current implementation of the Symbol widget in cs-web-lib was based off the MultiStateMonitor widget in CSStudio. The Phoebus Symbol widget implementation was not applied.
I've now updated this widget to behave like the Phoebus widget. Tests and snapshots have also been updated. We check whether the symbol should behave like MultiStateMonitor or Symbol, so both opi and bob file behaviours are preserved.
=> Update symbol widget

package-lock.json, package.json, rollup.config.mjs
Previously we were getting a lot of warnings thrown during `rollup` that the `use client` directive from the 'mui' package were ignored:
```
(!) node_modules/@mui/styled-engine/GlobalStyles/GlobalStyles.js (1:0): Module level directives cause errors when bundled, "use client" in "node_modules/@mui/styled-engine/GlobalStyles/GlobalStyles.js" was ignored.
/cs-web-lib/node_modules/@mui/styled-engine/GlobalStyles/GlobalStyles.js:1:0
1: 'use client';
^
2: 
3: import * as React from 'react';
```
This `use client` directive is used by the mui package to mark the module as client code and therefore should probably be preserved during the rollup. There is a package `rollup-preserve-directives` that can do this so I have added this and configured it in the rollup.config file.
=> Preserve 'use-client' directives during rollup

src/ui/widgets/Slideshow/slideshow.tsx
This warning is currently thrown when running the tests:
```
Warning: findDOMNode is deprecated and will be removed in the next major release. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
at Transition (/cs-web-lib/node_modules/react-transition-group/cjs/Transition.js:135:30)
at CSSTransition (/cs-web-lib/node_modules/react-transition-group/cjs/CSSTransition.js:120:35)
at SwitchTransition (/cs-web-lib/node_modules/react-transition-group/cjs/SwitchTransition.js:159:35)
at SwitchableWidget (/cs-web-lib/src/ui/widgets/Slideshow/slideshow.tsx:49:25)
at div
at div
at SlideshowComponent (/cs-web-lib/src/ui/widgets/Slideshow/slideshow.tsx:86:61)
```
I've followed the advice to pass a …
=> Fix findDOMNode deprecation warning in slideshow widget

src/misc/profilerCallback.ts
With React 18, it seems some of the properties of the onRender callback have changed:
- `phase` variable can now also be "nested-update", as well as "mount" and "update"
- `interactions` variable has been removed
Without these changes, tsc fails in machine status and other clients with this error:
```
src/app.tsx:107:46 - error TS2322: Type '(id: string, phase: "mount" | "update", actualDuration: number, baseDuration: number, startTime: number, commitTime: number, interactions: unknown) => void' is not assignable to type 'ProfilerOnRenderCallback'.
107         <Profiler id="Dynamic Page Profiler" onRender={onRenderCallback}>
src/app.tsx:107:46 - error TS2322: Type '(id: string, phase: "mount" | "update", actualDuration: number, baseDuration: number, startTime: number, commitTime: number) …
```
=> Update profiler callback properties for react 18

src/ui/widgets/createComponent.tsx
We are getting warnings in the tests when a widget is undefined:
```
Warning: Each child in a list should have a unique "key" prop.
Check the render method of `EmbeddedDisplay`. See https://reactjs.org/link/warning-keys for more information.
at Label
at EmbeddedDisplay (/home/rjaw/cs-web/cs-web-proto/node_modules/@diamondlightsource/cs-web-lib/dist/cjs/index.js:9941:42)
at LoadEmbedded (/home/rjaw/cs-web/cs-web-proto/src/app.tsx:33:39)
at Route (/home/rjaw/cs-web/cs-web-proto/node_modules/react-router/cjs/react-router.js:664:29)
at Switch (/home/rjaw/cs-web/cs-web-proto/node_modules/react-router/cjs/react-router.js:866:29)
at div
at Provider (/home/rjaw/cs-web/cs-web-proto/node_modules/react-redux/lib/components/Provider.js:21:20)
at App
at Router …
```
=> Add the key prop to the 'Error' component

src/types/font.test.ts, src/types/font.ts, src/ui/components/ContextMenu/contextMenu.module.css, src/ui/widgets/ChoiceButton/choiceButton.test.tsx, src/ui/widgets/DropDown/dropDown.module.css, src/ui/widgets/ProgressBar/progressBar.module.css, src/ui/widgets/SlideControl/slideControl.module.css, src/ui/widgets/Tabs/dynamicTabs.tsx, src/ui/widgets/Tabs/tabs.module.css, src/ui/widgets/XYPlot/xyPlotOptions.test.ts, src/ui/widgets/tooltip.module.css
Previously, font sizing in cs-web-lib used the [62.5% font-size trick](https://www.aleksandrhovhannisyan.com/blog/62-5-percent-font-size-trick/) for font-sizing, which requires client applications to set the root font size to 62.5% for fonts to appear the correct size. This isn't very transparent and there seem to be mixed reviews on using it. It causes issues when trying to use cs-web-lib in a client application that uses e.g. MUI components alongside bob screens.
I have swapped the font back to calculating REM from pixels by using the browser default font size of 16px and added a comment for context. This won't scale correctly if a browser user manually adjusts the browser default font size, but the .bob screens don't scale correctly anyway.
=> Update font sizing

src/ui/widgets/EmbeddedDisplay/bobParser.ts
Actions in bob files were previously parsed by `opiParseActions`, which didn't work due to small differences between actions in opi and bob files. These include:
- The `type` of action is lowercase in bob i.e. "open_display" but uppercase in opi
- bob files use the `target` property to determine if the new screen opens in a tab or in place of the current screen, rather than mode and position
- The path to the file to open is given by the `file` property rather than the `path` property in bob files
I created `bobParseActions` to correctly parse with these differences
=> Add bobParseActions

src/ui/widgets/EmbeddedDisplay/bobParser.test.ts, src/ui/widgets/EmbeddedDisplay/bobParser.ts
While testing a previous change in the bobParser I noticed that I was getting warnings in the console that a property could not be parsed. This didn't cause errors in the application as the property was optional. 
The problem is that a BOB file generated from Phoebus by default does not include the `alarm_sensitive_border` property. By default this is assumed to be _true_ and so the property is only added if the user sets it to _false_. 
I've added a separate bobParser version to use instead of the opiParser version. Also updated the tests to make sure the default version is reflected correctly.
TESTING: To test with and without this fix, use a BOB file generated by Phoebus that contains a `TextUpdate` widget.
=> Fix warnings in bobParser when alarmSensitive border property is missing

src/ui/widgets/EmbeddedDisplay/bobParser.ts, src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx, src/ui/widgets/GroupBox/__snapshots__/groupBox.test.tsx.snap, src/ui/widgets/GroupBox/groupBox.test.tsx, src/ui/widgets/GroupBox/groupBox.tsx
I have updated the GroupBox widget appearance, and pointed the widget mapping to correctly use GroupBox instead of GroupingContainer for bob files. None of the opi behaviour should be affected by these changes.
Changes:
- Phoebus group boxes come in 4 styles - Group Box, Title Bar, Line and None. These are now all included. The `style` property is parsed as `styleOpt`, in order to prevent confusion when passing the prop to a component (not doing so triggers an eslint warning `Style prop value must be an object`)
- Removed the `compat` property and set the style for GroupBox EmbeddedDisplays to the default groupbox style. This should give the same appearance as before
- Props were not being passed to the widget correctly due to missing GroupBoxProps in GroupBoxWidgetProps. This has now …
=> Update GroupBox widget

src/misc/fileContext.tsx, src/misc/index.ts, src/ui/widgets/index.ts, src/ui/widgets/widgetActions.ts
I implemented these changes to come up with a solution to issues I faced when creating a client application that opens and displays files.
Suggested changes:
- Allow new files to be opened at a new URL if wanted. Currently new files are opened at the same address, but a new entry is added to the history. This allows you to traverse file history but not customise URL based on the currently displayed file. Now you can optionally pass a pathname to open your new screen at. It might be worth also adding this to the removePage option, I'd appreciate any opinions?
- Export the executeAction hook so that non cs-web-lib components can trigger open/close page/tab events. Currently, actions such as opening a screen can only be called from inside an existing screen (either a .bob file or a json …
=> Modify and export addPage widget actions

src/ui/widgets/DynamicPage/dynamicPage.tsx
- Following a fix of the font scaling the font used to signal that a file had not been loaded was too large for the DynamicPage. This is just something I missed earlier and so easily fixable
Before:
After:
- The /img/x.png is used to fill the 'close' actionbutton within a DynamicPage. This image was not actually part of the library and relied on the client app having it. This image was only in cs-web-proto (as that was where it originated) but if the image was not in the client app then you would get an empty action button. What's more, it's not easy to include an image into a library - in fact I couldn't get this to work within our current rollup configuration. So instead I opted to use a unicode character which yields the same effect.
Before:  ![Screenshot from 2025-03-04 …
=> Replace 'x' image with unicode text and fix font scaling

src/ui/widgets/Image/image.tsx, src/ui/widgets/Symbol/__snapshots__/symbol.test.tsx.snap
I've added an objectPosition attribute, set to "top left", to the returned <img> component. I believe the default behaviour is for this to be set to "center" which would explain the behaviour. I don't if it would be better for there to be an option for this?
=> Fix image stretch to fit behaviour

src/colourscheme.ts, src/diamondTheme.ts, src/ui/widgets/ActionButton/__snapshots__/actionButton.test.tsx.snap, src/ui/widgets/ActionButton/actionButton.tsx, src/ui/widgets/EmbeddedDisplay/bobParser.test.ts, src/ui/widgets/EmbeddedDisplay/bobParser.ts, src/ui/widgets/EmbeddedDisplay/embeddedDisplay.tsx
I've changed the ActionButtonComponent so that it returns a MUI Button instead of a html button.
=> 84 replace action button with mui button

src/ui/widgets/Label/__snapshots__/label.test.tsx.snap, src/ui/widgets/Label/label.tsx, src/ui/widgets/Symbol/__snapshots__/symbol.test.tsx.snap
Forgot to add a border to the label widget.
=> Add border to label

src/ui/widgets/Input/__snapshots__/input.test.tsx.snap, src/ui/widgets/Input/input.tsx
Changed Input widget to use same border styling as Readback widget
=> Make input use same border stying as readback

src/types/position.ts, src/ui/hooks/useRules.ts, src/ui/widgets/EmbeddedDisplay/bobParser.ts, src/ui/widgets/EmbeddedDisplay/jsonParser.ts, src/ui/widgets/EmbeddedDisplay/opiParser.test.ts, src/ui/widgets/EmbeddedDisplay/opiParser.ts
Added x and y fields to the RelativePosition prop as Widgets expects a PositionProp, which can either be RelativePosition or AbsolutePosition, and therefore it wasn't possible to change the x and y fields of the PositionProp because they may not always exist.
=> Update widget rules not applying to nested properties

src/redux/store.ts, src/types/pv.test.ts, src/types/pv.ts
PV parser has been updated to correctly parse PV formulae and to parse PV starting with "=" to start with "eq://". "eq://" has been added to list of plugins in store.ts to enable formulae subscribe requests.
=> 81 pv formulae not supported
